defaults:
  - _self_

name: "TD3BC"

actor_lr: 1e-4
critic_lr: 1e-4
log_freq: 100
eval_freq: 1000
lambda_entropy: 0.0 

discount: 0.99
tau: 0.005
policy_noise: 0.0  # 0.1
noise_clip: 0.0  # 0.2
policy_freq: 2
alpha: 0.0  # 2.5

batch_size: 512
max_train_steps: 100000
# save_freq: 50000
normalize_states: True

reward_scale: 0.001

observation:
  vision: False
  pc: True

offline:
  data_dir: "/home/qianhui/Desktop/IsaacLab-dexret/symdex/symdex/teleop_logs/PickObjectEnv-v0_success"
  pattern: "*.h5"  # "*.h5"  # "PickObjectEnv-v0_*/*.h5"
  max_action: 1.0

checkpoint:
  load_path: null