defaults:
  - algo: symdex_algo
  - task: boxLift
  - logging: default
  - _self_

env_name: "boxLift-v0"
num_envs: 4096
device: 'cuda:0'
sim_device: ${.device}
rl_device: ${.device}
graphics_device_id: 0

seed: 42  # 42  # -1 for teleop
max_step: null
max_time: 36000 # in seconds
eval_headless: True
headless: True
max_episode_length: 500  # TODO: p90 of offline actions

info_track_keys: null # a list of keys to track in the info dict returned by env.step
info_track_step: ['all-step'] # ['last', 'all-episode', 'all-step'], whether to track the info in the
                      # last step or all steps. for all steps, whether to sum all values in episodes
                      # up or keep track per-step values
                      
artifact: null
artifact_critic: null
save_model: False

logger:   # for teleop data collection
  enable: False
  max_episodes: 5

replay:
  print_every: 5
  dataset_path: null  # path to dataset h5 file