defaults:
  - algo: symdex_algo
  - task: boxLift
  - logging: default
  - _self_

env_name: "boxLift-v0"
num_envs: 4096
device: 'cuda:0'
sim_device: ${.device}
rl_device: ${.device}
graphics_device_id: 0

seed: 42  # 42  # -1 for teleop
max_step: null
max_time: 36000 # in seconds
eval_headless: True
headless: True
                      
artifact: null
save_model: False
max_episode_length: 2000

logger: 
  enable: False
  max_episodes: 5  # for teleop data collection

replay:
  print_every: 5
  dataset_path: null  # path to dataset h5 file